### ISSUE TITLE
PS TV Help

### ISSUE THREAD

**Issue by talha007** [LiEnby/DolcePolce#2]
Sorry for being such a noob to this but how do I get Sceshell on the PS TV? I have QCMA and have it working on the PS TV but have no Idea what to do with this file any tutorial would be apperciated

**Comment by talha007** [comment]
So I have Vita Shell installed and have h-encore^2 as well now Im stumped as to where Im supposed to put these files

**Comment by LiEnby** [comment]
Into ur0:/tai
As well as adding an entry into config.txt

**Comment by LiEnby** [comment]
Or just use autoplugin. I think it has this now.
